// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJOSQXLkjgCI0BbHcyIc0UEo-Uhff8v7A',
    appId: '1:538440134819:web:d1ea1f849f5e45de958f16',
    messagingSenderId: '538440134819',
    projectId: 'todoapp-b7ee6',
    authDomain: 'todoapp-b7ee6.firebaseapp.com',
    storageBucket: 'todoapp-b7ee6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3oo1u_781TlBuYa1IDjWxtqUWyRadG0M',
    appId: '1:538440134819:android:309b7b09cac654d2958f16',
    messagingSenderId: '538440134819',
    projectId: 'todoapp-b7ee6',
    storageBucket: 'todoapp-b7ee6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCznfs4BtMv1w0je98PfhPsvJVHmvmroNo',
    appId: '1:538440134819:ios:4d101b68fe6475ec958f16',
    messagingSenderId: '538440134819',
    projectId: 'todoapp-b7ee6',
    storageBucket: 'todoapp-b7ee6.firebasestorage.app',
    iosBundleId: 'com.example.todoTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCznfs4BtMv1w0je98PfhPsvJVHmvmroNo',
    appId: '1:538440134819:ios:4d101b68fe6475ec958f16',
    messagingSenderId: '538440134819',
    projectId: 'todoapp-b7ee6',
    storageBucket: 'todoapp-b7ee6.firebasestorage.app',
    iosBundleId: 'com.example.todoTask',
  );
}
